AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - bookapp::book-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  BookServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.Hello::handleRequest
      Runtime: java8
      CodeUri: target/aws-test-1.0-SNAPSHOT-lambda-package.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
#        GetResource:
#          Type: Api
#          Properties:
#            Path: /{proxy+}
#            Method: any
        Api1:
          Type: Api
          Properties:
            Path: /testFuncJava
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /ping
            Method: ANY
        Api3:
          Type: Api
          Properties:
            Path: /
            Method: ANY
