AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - bookapp::book-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  BookServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: example.Hello::handleRequest
      Runtime: java11
      CodeUri: target/aws-test-1.0-SNAPSHOT-lambda-package.jar
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  BookServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/ping'
    Export:
      Name: BookServiceApi